Repository 4N1Z/Sorting-Searching-Algorithms, pull requests merged in 2022-10, with the labels that each got.

#12 Changed typos
  Searching/Binary-Search/in_Java.java
Labels: bug

#15 Add Radix Sort in Python
  Sorting/Radix Sort/in_Python.py
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#9 Added Interploation Search
  Searching/Interpolation-Search/in_C.c
Labels: enhancement, good first issue, Hacktoberfest

#16 Create QuickSort.java
  Sorting/QuickSort/QuickSort.java
Labels: enhancement, good first issue, Hacktoberfest

#17 Contribute bucket sort algorithm in java
  Sorting/Bucket-Sort/in_Java.java
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#43 Create in_Java.java
  Sorting/Selection Sort/in_Java.java
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#22 mergesort in java
  Sorting/Merge-Sort/in_Java.java
  Sorting/countsort/CountingSort.java
Labels: documentation, enhancement

#24 added selection sort in java
  Sorting/Selection-sort/in_Java.java
Labels: enhancement, good first issue, Hacktoberfest

#27 Create in_C++.cpp
  Sorting/Quick Sort/in_C++.cpp
Labels: enhancement, Hacktoberfest

#29 Create inCpp.cpp
  Searching/Binary-Search/inCpp.cpp
Labels: enhancement, good first issue, Hacktoberfest

#30 inCpp.cpp
  Sorting/Bubble Sort/inCpp.cpp
Labels: enhancement, good first issue, Hacktoberfest

#33 Added bubble sort in javascript
  Sorting/Bubble Sort/in_Javascript.js
Labels: enhancement, good first issue, Hacktoberfest

#38 Created Fibonacci Search in Java
  Searching/Fibonacci Search/in_Java.java
  Searching/Fibonacci Search/readme.md
Labels: enhancement, good first issue, Hacktoberfest

#49 Removed additional Selection Sort
  Sorting/Selection Sort/in_Java.java
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#52 deleted readme file and copied contents as comments in code file
  Searching/Fibonacci Search/in_Java.java
  Searching/Fibonacci Search/readme.md
Labels: help wanted, good first issue, Hacktoberfest, hacktoberfest-accepted

#6 linear searching in python
  Searching/Linear-Search/in_python.py
Labels: enhancement, good first issue, Hacktoberfest

#48 Added Fibonacci Search in C++
  Searching/Fibonacci Search/in_cpp.cpp
Labels: enhancement, good first issue, Hacktoberfest

#60 Added Merge Sorting in Javascript
  Sorting/Merge-Sort/in_JavaScript.js
Labels: documentation, enhancement, Hacktoberfest

#64 Selection sort using C
  Sorting/Selection-sort/in_C.c
Labels: enhancement, good first issue, Hacktoberfest

#54 Create Heap Sort
  inCPP.cpp
Labels: enhancement, Hacktoberfest

#55 Create Exponential search in c++
  Searching/inCPP.cpp
Labels: enhancement, Hacktoberfest

#76 Breadth First Search and Depth First Search for Binary Trees
  Searching/BFS/in_C++.cpp
  Searching/DFS/in_C++.cpp
  Searching/Linear-Search/in_html.html
Labels: documentation, Hacktoberfest

#96 Create in_C.c
  Sorting/Quick Sort/in_C.c
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#97 Create in_C.c
  Sorting/Merge-Sort/in_C.c
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#100 created Selection Sort in C++
  Sorting/Selection-sort/in_C++.cpp
Labels: documentation, good first issue, Hacktoberfest, hacktoberfest-accepted

#105 Create in_C.c
  Sorting/Bucket-Sort/in_C.c
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#106 Create in_python.py
  Sorting/countsort/in_python.py
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#107 Create in_python.py
  Sorting/Selection-sort/in_python.py
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#108 Create in_python.py
  Sorting/Merge-Sort/in_python.py
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#111 Update in_cpp.cpp
  Searching/Linear-Search/in_cpp.cpp
Labels: documentation

#112 Update in_C++.cpp
  Searching/Binary-Search/in_C++.cpp
Labels: documentation

#119 added main() and also added example explanation.
  Searching/Linear-Search/in_Java.java
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#123 Create in_Java.java
  Searching/DFS/in_Java.java
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#124 Create in_Java.java
  Searching/BFS/in_Java.java
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#121 Created Bucket Sort in c++ with proper explanation
  Searching/Jump-Search/in_JavaScript.js
Labels: duplicate

#80 Jump Search in python
  Searching/Jump-Search/in_python.py
Labels: documentation, enhancement, Hacktoberfest

#117 Bucket sort in_python
  Sorting/Heap Sort/in_python.py
Labels: duplicate

#133 Create in_Python.py
  Shell Short/in_Python.py
Labels: enhancement, Hacktoberfest

#171 Added Interpolation-search in python
  Searching/Interpolation-Search/in_python.py
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#179 Dart bubble sort
  Sorting/Bubble Sort/Bubblesort.md
  Sorting/Bubble Sort/in_dart.dart
Labels: enhancement, good first issue

#114 Linear Search in Go language
  Searching/Linear-Search/in_go.go
Labels: good first issue, Hacktoberfest

#170 Added Cyclic Sort and update README.md
  README.md
  Sorting/CyclicSort/in_Java.java
Labels: documentation, enhancement, Hacktoberfest

#190 Fibonacci Search in C
  Searching/Fibonacci Search/in_C.c
Labels: documentation, enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#168 pancake sorting
  Searching/inCPP.cpp
  Sorting/Pancake Sorting/inCpp.cpp
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted

#191 Python Program for BFS traversal
  Searching/Fibonacci Search/in_C.c
  Searching/in_Python.py
Labels: documentation, enhancement, Hacktoberfest

#208 added golang code of bubble sort with explaination
  Sorting/Bubble Sort/in_Golang.go
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#213 Updated README.md and Made changes to Searching Directory
  README.md
  Searching/in_Python.py
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted

#167 Create in_CPP.cpp
  Searching/Interpolation-Search/in_CPP.cpp
Labels: enhancement, good first issue, Hacktoberfest
